// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9QcR8Du2HRGsNbDOAa2FCy4kFU9xD3II',
    appId: '1:371307768271:web:d803788121d0fff3140aba',
    messagingSenderId: '371307768271',
    projectId: 'sapfd-80a0a',
    authDomain: 'sapfd-80a0a.firebaseapp.com',
    storageBucket: 'sapfd-80a0a.appspot.com',
    measurementId: 'G-NZW4XWW2L0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiocXK62Yg5LJfRlm7f5RwuZVIQ7yA1YA',
    appId: '1:371307768271:android:baf211d4d6d64d61140aba',
    messagingSenderId: '371307768271',
    projectId: 'sapfd-80a0a',
    storageBucket: 'sapfd-80a0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs03XNeeHus-gpFcIWsV5Hb79R48jSdXA',
    appId: '1:371307768271:ios:9212ca743d0ac9a3140aba',
    messagingSenderId: '371307768271',
    projectId: 'sapfd-80a0a',
    storageBucket: 'sapfd-80a0a.appspot.com',
    iosBundleId: 'com.example.sapfd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs03XNeeHus-gpFcIWsV5Hb79R48jSdXA',
    appId: '1:371307768271:ios:86bd0109e7ab1083140aba',
    messagingSenderId: '371307768271',
    projectId: 'sapfd-80a0a',
    storageBucket: 'sapfd-80a0a.appspot.com',
    iosBundleId: 'com.example.sapfd.RunnerTests',
  );
}
