// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlCGW1KeFvjUTmzV7GZH5A2qq6Pf4vgvk',
    appId: '1:838923326580:web:1ad29da2c703d101cb2d21',
    messagingSenderId: '838923326580',
    projectId: 'futur-6d31c',
    authDomain: 'futur-6d31c.firebaseapp.com',
    storageBucket: 'futur-6d31c.appspot.com',
    measurementId: 'G-WX7YQSC2ES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU2gF9DrDf7Ae8rCrWFfpBDJxsxSvPDcQ',
    appId: '1:838923326580:android:252dd09258c865bccb2d21',
    messagingSenderId: '838923326580',
    projectId: 'futur-6d31c',
    storageBucket: 'futur-6d31c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU6_feWsAHxfIYf9J2b-lFyA00GXYVaPQ',
    appId: '1:838923326580:ios:23b2e8dab7861e4bcb2d21',
    messagingSenderId: '838923326580',
    projectId: 'futur-6d31c',
    storageBucket: 'futur-6d31c.appspot.com',
    iosBundleId: 'com.example.sapfd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU6_feWsAHxfIYf9J2b-lFyA00GXYVaPQ',
    appId: '1:838923326580:ios:ecf6cd78943c25f8cb2d21',
    messagingSenderId: '838923326580',
    projectId: 'futur-6d31c',
    storageBucket: 'futur-6d31c.appspot.com',
    iosBundleId: 'com.example.sapfd.RunnerTests',
  );
}
